/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AllocationResult = IDL.Record({
  'unmatchedStudents' : IDL.Vec(IDL.Nat),
  'matches' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Student = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'addProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'addStudent' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'allocateProjects' : IDL.Func([], [AllocationResult], []),
  'clearAll' : IDL.Func([], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getLatestAllocation' : IDL.Func([], [IDL.Opt(AllocationResult)], ['query']),
  'getPreferences' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(IDL.Nat))],
      ['query'],
    ),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'matchedCount' : IDL.Nat,
          'totalStudents' : IDL.Nat,
          'totalProjects' : IDL.Nat,
          'unmatchedCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'setPreferences' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AllocationResult = IDL.Record({
    'unmatchedStudents' : IDL.Vec(IDL.Nat),
    'matches' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Student = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  
  return IDL.Service({
    'addProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'addStudent' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'allocateProjects' : IDL.Func([], [AllocationResult], []),
    'clearAll' : IDL.Func([], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getLatestAllocation' : IDL.Func(
        [],
        [IDL.Opt(AllocationResult)],
        ['query'],
      ),
    'getPreferences' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(IDL.Nat))],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'matchedCount' : IDL.Nat,
            'totalStudents' : IDL.Nat,
            'totalProjects' : IDL.Nat,
            'unmatchedCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'setPreferences' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };