/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllocationResult {
  'unmatchedStudents' : Array<bigint>,
  'matches' : Array<[bigint, bigint]>,
}
export interface Project {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Student { 'id' : bigint, 'name' : string }
export interface _SERVICE {
  'addProject' : ActorMethod<[bigint, string, string], boolean>,
  'addStudent' : ActorMethod<[bigint, string], boolean>,
  'allocateProjects' : ActorMethod<[], AllocationResult>,
  'clearAll' : ActorMethod<[], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'deleteStudent' : ActorMethod<[bigint], boolean>,
  'getLatestAllocation' : ActorMethod<[], [] | [AllocationResult]>,
  'getPreferences' : ActorMethod<[bigint], [] | [Array<bigint>]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getStats' : ActorMethod<
    [],
    {
      'matchedCount' : bigint,
      'totalStudents' : bigint,
      'totalProjects' : bigint,
      'unmatchedCount' : bigint,
    }
  >,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'setPreferences' : ActorMethod<[bigint, Array<bigint>], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];